name: generateSnake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows you to run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutRepo
        uses: actions/checkout@v3

      - name: generateSnakeFiles
        uses: Platane/snk@v3
        with:
          github_user_name: vibrant-impact
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: commitAndPush
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          mkdir -p assets
          git add assets/github-contribution-grid-snake*.svg
          git commit -m "update snake animation" || exit 0
          git push
