name: generateStats
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Dark Mode Stats
      - name: generateDarkStats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          path: assets/stats-dark.svg
          options: "username=vibrant-impact&theme=radical&hide_border=true"
          token: ${{ secrets.GH_TOKEN }}

      # Light Mode Stats
      - name: generateLightStats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          path: assets/stats-light.svg
          options: "username=vibrant-impact&theme=vibrant&hide_border=true"
          token: ${{ secrets.GH_TOKEN }}

      - name: commitAndPush
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          mkdir -p assets
          git add assets/*.svg
          git commit -m "update responsive stats" || exit 0
          git push
